name: Tiqets Assignment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          poetry run python -m unittest discover src/tests
      - name: Lint with ruff
        run: |
          poetry run ruff check .
      - name: Lint with flake8
        run: |
          poetry run flake8 .
      - name: Check imports with isort
        run: |
          poetry run isort . --check-only
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag tiqets-assignment:latest
      - name: Run application in Docker container
        run: |
          mkdir -p output
          docker run tiqets-assignment:latest run data/orders.csv data/barcodes.csv output/result.csv
          
          if [ -f output/result.csv ]; then
            echo "Application ran successfully and produced output."
            cat output/result.csv
          else
            echo "Application failed to produce output file."
            exit 1
          fi
      - name: Upload output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: process-result
          path: output/result.csv