name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          poetry run python -m unittest discover src/tests
      - name: Lint with ruff
        run: |
          poetry run ruff check .
      - name: Check imports with isort
        run: |
          poetry run isort . --check-only
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag tiqets-assignments:$(date +%s)
